# Indexes for the virtual enterprise SIEM.

[idp]
homePath   = $SPLUNK_DB/idp/db
coldPath   = $SPLUNK_DB/idp/colddb
thawedPath = $SPLUNK_DB/idp/thaweddb

[app]
homePath   = $SPLUNK_DB/app/db
coldPath   = $SPLUNK_DB/app/colddb
thawedPath = $SPLUNK_DB/app/thaweddb

[network]
homePath   = $SPLUNK_DB/network/db
coldPath   = $SPLUNK_DB/network/colddb
thawedPath = $SPLUNK_DB/network/thaweddb

[cloudflare]
homePath   = $SPLUNK_DB/cloudflare/db
coldPath   = $SPLUNK_DB/cloudflare/colddb
thawedPath = $SPLUNK_DB/cloudflare/thaweddb

[onprem]
homePath   = $SPLUNK_DB/onprem/db
coldPath   = $SPLUNK_DB/onprem/colddb
thawedPath = $SPLUNK_DB/onprem/thaweddb

[sut_audit]
homePath   = $SPLUNK_DB/sut_audit/db
coldPath   = $SPLUNK_DB/sut_audit/colddb
thawedPath = $SPLUNK_DB/sut_audit/thaweddb
